inherit_mode:
  merge:
    - Exclude

inherit_from: ./.rubocop-common.yml

AllCops:
  TargetRubyVersion: 3.0

########## Style ############

Style/RequireOrder:
  Exclude:
    - 'lib/request_pipeline.rb'
