name: Main

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    env:
      BUNDLE_WITH: lint
      BUNDLE_WITHOUT: development test
    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby 3.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true

      - name: Rubocop
        run: bundle exec rubocop --format progress

  test:
    needs:
      - lint
    runs-on: ubuntu-latest
    name: Test Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.0"
          - "3.1"
          - "3.2"
          - "3.3"
          - "3.4"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: RSpec
        run: bundle exec rspec
